language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: 2af10d5f1ce67fdc92ad911e571a4af74e3d3a4fdf3ac8a0456d5a68d9cd7152
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
before_deploy:
- npm run build
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: A0i4PrWuP0RkSnUcMwgb4FvYBf/2sb/4FCde2Jo/FohwWh2MuPqf6TJ7PU2SCoJGY6iAnInHyzQ4F77dS5Y4aKQVaEi3ko8bjw3DDF56O306GIAfiabAvdEkOF3v8z3J4cilC6REpBRs+WBY/XU/zv2fYoUNRSv855MUUnvIhqleyv7j9ic5sw6Dw74RtvCsL+lKgUcaGv3KBAn0UfNKB4DHM5lRnSEf5VjGK3GVND/+qRUwJtZm7GlwWTqEWaM/SQT6bywYC1agwTWU6/pBs1iN+HriHyIRwYBlXxEWbuhd5pD3UDDYxZIZ4iCnCyTHFADXpxU06e4wM3QFMAiUzWSvDLqg9xgwRL8jM/5QngXd4pw112Zt4NjY/hN8qsolr0DeHLBAGyMoX5vhKZZ5qxjtNKgLcOgouH0vflFrcITNXk/Z7RBtyrmRD07ko81+rMqgbinX4/FjNerf+kCMS48LHI0jJnp/XWs8LM7k95zplRg3BfsDwD4mOmOpGY3ol5moH4d5Bj7ED8WMFU9VN8WFgj+gO9aihbqJx62gKLLXUFxrvdueTOppD8wpP6SqckteWwQgUF0pA8o2RSrVQHhTL+WnIjJzPuQ1AYtd8NHwzm5zMnXIIMzhD9s6j4ytAujmrkwsbPpoUeynCqiCozE0ETjTlflGDFwPTcOLK+c=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
